import fs from "fs";
import path from "path";
import PDFDocument from "pdfkit";

const writeSectionTitle = (doc, title) => {
  doc.moveDown();
  doc.font("Helvetica-Bold").fontSize(15).text(title, { underline: true });
  doc.moveDown(0.5);
};

const writeParagraph = (doc, text) => {
  if (!text) return;
  doc.font("Helvetica").fontSize(11).text(text, { align: "justify", lineGap: 2 });
  doc.moveDown(0.4);
};

const writeLine = (doc, text) => {
  if (!text) return;
  doc.font("Helvetica").fontSize(11).text(text, { align: "left", lineGap: 1 });
};

const ensurePageRoom = (doc) => {
  if (doc.y > 740) {
    doc.addPage();
  }
};

export const generatePdfReport = async ({ generatedAt, summary, keyMetrics = [], sections = [] }) => {
  const reportsDir = process.env.REPORTS_DIR || "./reports";
  if (!fs.existsSync(reportsDir)) fs.mkdirSync(reportsDir, { recursive: true });

  const filename = `gridguard-report-${Date.now()}.pdf`;
  const filePath = path.join(reportsDir, filename);

  const doc = new PDFDocument({ size: "A4", margin: 50 });
  const stream = fs.createWriteStream(filePath);
  doc.pipe(stream);

  doc.font("Helvetica-Bold").fontSize(22).text("GRIDGUARD AI 4.0", { align: "left" });
  doc.font("Helvetica-Bold").fontSize(17).text("National Smart Grid Executive Intelligence Report", { align: "left" });
  doc.moveDown();
  doc.font("Helvetica").fontSize(11).text(`Generated: ${generatedAt || new Date().toISOString()}`);
  doc.text("Scope: National operational risk, theft intelligence, transformer reliability, alert posture, and recommended actions.");
  doc.text("Source: Live platform data (regions, alerts, transformer telemetry, meter anomalies, and reading streams).");
  doc.moveDown(0.8);

  writeSectionTitle(doc, "Executive Narrative");
  const paragraphs = String(summary || "Summary unavailable")
    .split(/\n{2,}/)
    .map((p) => p.trim())
    .filter(Boolean);
  if (!paragraphs.length) writeParagraph(doc, "Summary unavailable.");
  paragraphs.forEach((p) => {
    ensurePageRoom(doc);
    writeParagraph(doc, p);
  });

  writeSectionTitle(doc, "Key Metrics");
  if (!keyMetrics.length) {
    writeLine(doc, "No key metrics available.");
  } else {
    keyMetrics.forEach((item) => {
      ensurePageRoom(doc);
      writeLine(doc, `${item.label}: ${item.value}`);
    });
  }

  sections.forEach((section) => {
    ensurePageRoom(doc);
    writeSectionTitle(doc, section.title);

    (section.lines || []).forEach((line) => {
      ensurePageRoom(doc);
      writeLine(doc, line);
    });

    if (section.lines?.length) doc.moveDown(0.3);

    (section.items || []).forEach((item) => {
      ensurePageRoom(doc);
      writeLine(doc, `- ${item}`);
    });
  });

  doc.moveDown();
  doc.font("Helvetica").fontSize(9).text("Generated by GRIDGUARD AI 4.0 automated reporting engine.", { align: "left" });

  doc.end();

  await new Promise((resolve, reject) => {
    stream.on("finish", resolve);
    stream.on("error", reject);
  });

  return filePath;
};
